# Generated by Django 5.0.3 on 2024-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('logtime', models.CharField(max_length=255)),
            ],
        ),
    ]
